# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 08:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170711_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
